<?php

namespace Tgallice\FBMessenger;

/**
 * https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags
 */
interface MessagingTag
{
    const BUSINESS_PRODUCTIVITY = 'BUSINESS_PRODUCTIVITY';

    const COMMUNITY_ALERT = 'COMMUNITY_ALERT';

    const CONFIRMED_EVENT_REMINDER = 'CONFIRMED_EVENT_REMINDER';

    const NON_PROMOTIONAL_SUBSCRIPTION = 'NON_PROMOTIONAL_SUBSCRIPTION';

    const PAIRING_UPDATE = 'PAIRING_UPDATE';

    const APPLICATION_UPDATE = 'APPLICATION_UPDATE';

    const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE';

    const PAYMENT_UPDATE = 'PAYMENT_UPDATE';

    const PERSONAL_FINANCE_UPDATE = 'PERSONAL_FINANCE_UPDATE';

    const SHIPPING_UPDATE = 'SHIPPING_UPDATE';

    const RESERVATION_UPDATE = 'RESERVATION_UPDATE';

    const ISSUE_RESOLUTION = 'ISSUE_RESOLUTION';

    const APPOINTMENT_UPDATE = 'APPOINTMENT_UPDATE';

    const GAME_EVENT = 'GAME_EVENT';

    const TRANSPORTATION_UPDATE = 'TRANSPORTATION_UPDATE';

    const FEATURE_FUNCTIONALITY_UPDATE = 'FEATURE_FUNCTIONALITY_UPDATE';

    const TICKET_UPDATE = 'TICKET_UPDATE';
}
